### PR TITLE
Fixed file header

### PR DESCRIPTION
**Pull request by nicoboyce**
Should solve the css issue

### CODE REVIEW

**Comment by freakboy3742** [comment]
It's not clear to me which CSS issue you're referring to...

**Comment by danyeaw** [comment]
I agree that it would have been helpful to have more details of what you were trying to fix. This is what the page looks like for me:
screenshot from 2018-03-31 21-58-55
Thanks for the contribution :+1:

**Comment by nicoboyce** [comment]
Sorry, new to this sort of thing. There was context in the gitter chat I
should have included.

**Comment by freakboy3742** [comment]
This is a known (and reported) problem with Read The Docs - see rtfd/readthedocs.org#3715. If you build the docs locally, you'll see that it renders fine.

**Comment by danyeaw** [comment]
@freakboy3742 That explains why everything looked great when I built Sphinx locally using this PR fork

**Pull request merged**
