### PR TITLE
added test case for command module add method

### PR DESCRIPTION
**Pull request by kartik-karz**
## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by kartik-karz** [comment]
Yes @freakboy3742, one of the child statement under a conditional statement was not getting executed since it required both app and widget to be true... having this patch increases the percentage by 2% or so since the hidden child also gets executed.

**Comment by kartik-karz** [comment]
closed by mistake

**Comment by kartik-karz** [comment]
@freakboy3742 Can I get this merged?

**Comment by kartik-karz** [comment]
```
    def add(self, *values):
        <---if self.widget and self.widget.app != None:--->
            self.widget.app.commands.add(*values) # doesn't get executed
        self._values.update(values)
        if self.on_change:
            self.on_change()
```
@freakboy3742 I have no idea what other documentation I should have provided... I mean this was like the simplest thing I thought I should do such that it would be merged soon since the docs mentioned that even a single percent of an increase in the coverage would mean a lot...

**Comment by freakboy3742** [comment]
Yes, increasing by even 1% is desirable. But the goal here isn't to "increase coverage at all cost". It's to increase the quality of the code by increasing the amount of the codebase that is tested. The coverage number is the *start* of the process, not the end.

In this case, you're not just increasing 1 line of coverage. You're testing the case that if a command set  is associated with a widget that has been added to an app, the commands in the set are added to the app. 

So where is the verification that this happens? All you've verified here is that the code runs without raising an error - you're not testing any actual functionality. Admittedly, the existing test is weak in this regard; it should *also* be testing whether the commands have been registered - and confirming that they're not. 

You're also testing this case by setting the app as a *class* property, not as a widget property - so you're not replicating real-world conditions, you're doing the bare minimum needed to increase coverage by one line.

And, you've done this by just adding ~20 lines of code to the bottom of an existing test, most of which are identical to the 20 lines above, with no comments or explanation of what you've done.

To take an extreme example: Why are there different test methods *at all*? Can't we just have one big test method that runs *all* the code? That would get the same amount of coverage as splitting the tests into lots of separate tests.

The reason? Tests are, in themselves, a form of documentation. The test name gives an indication of what is being tested. If the reason for the test can't be expressed in a simple title, then you can add documentation to the start of the test. Or, if the situation requires a complex setup, you can put comments in the code to explain what you're doing, and why you're doing it.

**Comment by kartik-karz** [comment]
Okay

**Pull request closed without merging**
