### PR TITLE
Add set_full_screen() stubs to window.py implementations

### PR DESCRIPTION
**Pull request by bobm123**
EDIT: See comments below 

I added a setter method to toga_dummy\window.py for is_full_screen property. Then added a few lines to test_full_screen_set() so that it tests both reading and writing. If I understand correctly, an additional benefit of testing the setter method is to ensure the _impl method is invoked.

I'd like to continue working on this adding additional test for window.py, but would like to make sure I am on the right track, especially w.r.t changes/addition to toga_dummy\window.py

Best Regards,
Bob Marchese

Improves test coverage on window.py

## PR Checklist:

- [x ] All new features have been tested
- [x ] All new features have been documented
- [x ] I have read the **CONTRIBUTING.md** file
- [ x] I will abide by the code of conduct

### CODE REVIEW

**Comment by bobm123** [comment]
Clearly adding set is_full_screen to the dummy implementation has broken each of the actualy implementation tests. Sorry about that.

Should I add stubs to each of the implementation's window.py :
```
    def set_full_screen(self, is_full_screen):
        pass
```
Or should I back out these changes in start over on a different test?

Thanks, Bob M

**Comment by bobm123** [comment]
It looks like the changes I made to test_window.py have been overtaken by events with the recent merge #517. I'm glad to see the test coverage improved.

Is there any benefit to keeping the stub function set_full_screen() I added to the implementations? It seemed like they were missing but if they're not needed please let me know and we can just cancel this PR.

Thanks,
Bob M

**Comment by phildini** [comment]
Should these actually raise a `NotImplemented` error? And do we already do that if you're calling a method that doesn't yet exist in an implementation?

I don't think having these stubs is a bad idea, but it's pretty low-signal what happens when you call one of them right now.

**Comment by bobm123** [comment]
Thanks for the feedback. Here's how I was looking at the issue (or non-issue as the case may be ;-) )

It seemed like set_full_screen() was missing from the dummmy implementation since toga_gtk() already had a real implementation. So I added a setter to toga_dummy/window.py. But that broke several other implementations, so I added the stubs.

If these changes don't add value, let's cancel this PR and move on. I won't feel bad or anything, I'm just trying to get familiar with the codebase and processes here.

Thanks for looking at this!

Best Regards,
Bob M

**Pull request merged**
