### PR TITLE
Refactoring of the Tree widget [Core][Cocoa] [WIP]

### PR DESCRIPTION
**Pull request by Dayof**
Example code to test : https://gist.github.com/Dayof/450510e713fa76abee588b51eb742da7

### CODE REVIEW

**Comment by Dayof** [comment]
This new API enables the creation of a tree through:

- Dictionary : example code https://gist.github.com/Dayof/3f47ea4401828326efff82775a5eb255
- Node by node : example code https://gist.github.com/Dayof/44459029cbd2c0585c2c47d2bd6ed8d2
- From a data source [WIP] : example code ...

**Comment by Dayof** [comment]
Features : 

- Insert headings (issue #202 remains) : https://gist.github.com/Dayof/a3928d173198acbd3e7e5341076bd630
- Insert nodes : https://gist.github.com/Dayof/44459029cbd2c0585c2c47d2bd6ed8d2
- Insert icon : https://gist.github.com/Dayof/cd11e9ec0150251d392461d597e94530

**Comment by freakboy3742** [comment]
The API design here looks *awesome*. My only comment would be about the entry points on case 3 (an independent data source) - If I'm reading that correctly, the three required entry points for an independent data source are:
* `roots()`
* `has_children_by_node()`
* `children_by_node()`

The other methods in the example code are required because of the way the example is constructed.  Have I understood this correctly? If so:

* We can probably simplify the naming - `has_children` and `children` is probably sufficient
* Is there a reason you need *both* a `has_children` and `children` entry point? Isn't `has_children` just `children() is not None`?
* Would it be possible to put these "functional" parts of the API behind an attribute to separate the namespace? The use case for (3) is when you have a data structure that you want to render on a tree. On such a data structure, it wouldn't be unusual to have a `children` attribute - which means you then have a name collision between the API you want to use natively, and the API that Toga requires as a data source. An option here is to require that a "Toga data source" doesn't access `self.children()` directly, but looks for a `self._data.children()`. In the simple case, you could make the `_data` attribute return `self`; but in the more complex case, you could completely separate the data source from the API Toga requires for that data source.

Does that make sense?

**Comment by Dayof** [comment]
Thanks for the reviewing @freakboy3742 !

- I've made the modification about the entry points names e the necessity about the ``has_children_by_node()`` on the last commit.
- The last part I dind't understand very well, if on the ``Toga`` side I set ``self._data = tree`` and then access ``self._data.children()`` to interact with the class constructed by the user, would have a problem?

**Pull request merged**
