### PR TITLE
Table selection issue 401

### PR DESCRIPTION
**Pull request by go8ose**
I'm altering toga.widgets.Table so it initialises the ._selection attribute. 

In #401 I noticed if a user hasn't made a selection in a table, but you check the Tables selection a AttributeError is thrown. The documentation says None should be returned.

## PR Checklist:

- [x] All new features have been tested
- [ ] All new features have been documented
- [ ] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by goanpeca** [comment]
@go8ose maybe a screenshot (before/after) could help?

**Comment by go8ose** [comment]
@goanpeca The change I've made is a one line change. I don't expect any visual alteration due to this. What were you thinking a screenshot would help with? (And a screenshot of what)?

This change is only to avoid an exception being thrown, as I've described in #401.

**Comment by goanpeca** [comment]
I thought the selection changes were supposed to be visible on the table widget

**Comment by go8ose** [comment]
@goanpeca When I've been using a table widget on macOS, the selection changes have been visible. I'm not trying to suggest I've found a problem like that. The error I've found is when the user has not made any selection choice, and hence there is no current selection in the table. If you have code that happens to check for a selection at that time, an exception is thrown.

**Comment by goanpeca** [comment]
Understood!

**Pull request merged**
