### PR TITLE
[WIP] Get tutorial 2 working with the winforms backend

### PR DESCRIPTION
**Pull request by clokep**
In order to learn some of the internals of toga I've been working at trying to get the winforms backend working for [tutorial 2](https://toga.readthedocs.io/en/latest/tutorial/tutorial-2.html). This involves implementing some new components for the winforms backend:
* `SplitContainer` (partially done)
* `Table` (done)
* `Command` (not started)

### CODE REVIEW

**Comment by clokep** [comment]
Unfortunately this is bombing out when running, it works OK if I return `right_container` or `left_container` from the `build` function, but not when I return `split`. It complains about `_container` being `None`, thus having no `_impl` attribute (sorry I don't have the exact stack trace, not on my Windows machine at the moment!)

Some talk on Gitter about this:
> clokep: So I'm looking at making the second demo work with winforms (https://toga.readthedocs.io/en/latest/tutorial/tutorial-2.html), I'm making some progress it seems, but I'm stuck at some point...how does an widget get it's `_container` set? Nothing seems to set it, but when I return `split`, the window seems to assume `_container` is set already?
>
> freakboy3742: @clokep So this is one of the interesting internal pieces of Toga. A Box is a layout element, but doesn’t have an underlying actual widget - it’s just a way of specifying layout information. So, if you construct a box containing a box containing a box containing a button, there’s only one actual system widget - the button.
However, you still need to have a widget to “hold” the button - and that’s the container.
The container is generated behind the scenes when you display a widget that doesn’t have an _impl, at the point you add content to a window.
If you look at the core implementation of the setter for `container`, you’ll see that it checks for whether the widget has an `_impl`; if it does, it gets used as the `_container`, otherwise a new `_container` is created and the widget is set as the content of the container.
In the case of a widget like SplitContainer - the same thing then needs to happen one layer down.
The SplitContainer has an `_impl`, so it is used as the container for the main window. However, each of the split panels then needs to do the same “does my content have an `_impl`” dance.
When you set the container for the “top level” widget that is being added to the window (or split pane) that triggers set_container on each child widget of the top level widget, which physically adds the widget to the container.
Does that make sense?

I've tried internalizing that, but have been unable to get this to work still... hoping for some guidance on what to try next!

**Comment by clokep** [comment]
The actual stack trace:

```bash
$ python -m demo
Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\python36-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\clokep\toga\demo.py", line 94, in <module>
    app.main_loop()
  File "c:\users\clokep\toga\src\winforms\toga_winforms\app.py", line 49, in main_loop
    self._startup()
  File "c:\users\clokep\toga\src\winforms\toga_winforms\app.py", line 41, in _startup
    self.startup()
  File "c:\users\clokep\toga\src\core\toga\interface\app.py", line 125, in startup
    self.main_window.content = self._startup_method(self)
  File "c:\users\clokep\toga\src\core\toga\interface\window.py", line 160, in content
    self._set_content(widget)
  File "c:\users\clokep\toga\src\winforms\toga_winforms\window.py", line 26, in _set_content
    self._impl.Controls.Add(widget._container._impl)
AttributeError: 'NoneType' object has no attribute '_impl'
```

**Comment by voltagex** [comment]
@clokep can you provide some info on how you're setting this up to run from your code, rather than upstream toga?

**Comment by freakboy3742** [comment]
@voltagex To check out a WIP branch, a git checkout of the toga repository, and run `pip install -e .` in the `core` and `winforms` backends. That will "install as editable" the two modules that you'll be working with.

**Comment by clokep** [comment]
@voltagex It's pretty much like what @freakboy3742 said, but it's just creating editable installations:
`pip install -e src/core -e src/winforms -e .`, order is important so you install all locally.

The script I'm running is from https://github.com/pybee/toga/blob/7635a9c44e86a28bdefb53d966f29dfa960d2f10/docs/tutorial/tutorial-2.rst, but I can paste it somewhere else if that's helpful. (With the `toga.Command` lines commented out since I didn't implement that yet!)

I'm running it as `python -m demo`.

**Comment by voltagex** [comment]
Aha! I was wondering about those Command calls. Thanks to both of you for
your help.

**Comment by voltagex** [comment]
Command should now be implemented enough in master for the demo to run, pending this Container issue

**Comment by clokep** [comment]
Awesome! 👍 I'll rebase this on top of master at some point.

**Comment by clokep** [comment]
Rebased this, but haven't had a chance to try it again yet.

**Comment by leec1979** [comment]
I'm working through the tutorial on Windows and hitting some problems in Toga 0.2.15 that look like they've already been addressed in master. Is there a getting started guide for working on the Toga code? I'd like to help with Windows if I can but don't want to get in the way if someone is already working on it.

**Comment by freakboy3742** [comment]
@leec1979 Unfortunately, no - we don't have a starter guide for Toga (that's definitely something we need, though!)

There have been a few improvements on the Windows backend after 0.2.15 was released, but I'm not aware of anyone *actively* working on the Windows backend at the moment - so anything is essentially fair game!

**Comment by voltagex** [comment]
I was looking at this some time ago. Happy to help although my time is
somewhat limited.

**Comment by clokep** [comment]
Hmm...looks like this needs a rebase...and someone else added the `Table` class already. I'll see if I can look at this again soon.

**Comment by leec1979** [comment]
@freakboy3742, I'll try and put a contributors starter guide together as it seems like there's some work going on from other people in this area by @clokep and others.  It may take a week or two as I don't have much free time but I'll see what I can do.

**Comment by leec1979** [comment]
I've just spotted that there is already a how to for contributing to Toga. I've no idea how I missed that before.

In that case I'll wait to see how @clokep gets on with the rebase work before trying to help and making things even messier :)

**Comment by clokep** [comment]
@leec1979 So I did rebase this and I pushed, but I didn't test this since I wasn't on my Windows machine. I probably won't have time to look back at this for a couple of weeks though, so feel free to play with it and see if you can get it working! 👍

**Comment by leec1979** [comment]
@clokep, will do. Thanks turning that around so quickly.

**Comment by leec1979** [comment]
FYI I'm currently seeing this stack trace when running tutorial 2 from master.

`Unhandled Exception: Python.Runtime.PythonException: AttributeError : module 'toga_winforms.factory' has no attribute 'ScrollContainer'
   at Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()`

That's a reasonable error as there is indeed no ScrollContainer in there. I'll see if I can make any headway with it this weekend.

By the way this is without @clokep latest commit as the pull request hasn't been merged into master yet. Is there a way I can pull that commit into my local checkout?

**Comment by clokep** [comment]
@leec1979 there's many different ways, but the way I would personally do it:

```bash
git remote add clokep https://github.com/clokep/toga.git
git fetch clokep
```

At this point you'll have all the commits from my fork, so you can either checkout the `clokep/winforms-demo2` branch or you could cherry-pick the commit onto your own branch.

**Comment by clokep** [comment]
See #256.

**Pull request closed without merging**
