### PR TITLE
Cleanup imports

### PR DESCRIPTION
**Pull request by danyeaw**
I would like to see as part of our Beekeeper checks us run pyflakes/pep8 style checks. It would help improve quality, consistency, and people rather hear nitpicky stuff from a computer rather than a human :)

As part of getting ready for this, I have started with cleanup all of the import statements to align with the Google formatting:
Imports should be grouped with the order being most generic to least generic:

    standard library imports
    third-party imports
    application-specific imports

Within each grouping, imports should be sorted lexicographically, ignoring case, according to each module's full package path.

### CODE REVIEW

**Comment by freakboy3742** [comment]
There already is a pep8 check (although it's spelled pycodestyle, which is new, preferred name for pep8); however, it's evidently not configured to do import sort order checks. No objection to adding that to the pycodestyle configuration, though.

**Comment by goanpeca** [comment]
There is a nice library called http://isort.readthedocs.io/en/latest/ pretty cool and usefull

**Comment by danyeaw** [comment]
@freakboy3742 Oh, nice. I didn't see a specific CI test being run that referenced code style, so I just assumed it wasn't being done yet. Please excuse my ignorance :relaxed:

**Comment by danyeaw** [comment]
@goanpeca I created a new issue over at beefore and noticed you were working on pydoctest, maybe we could work together on integrating more tests.

**Comment by goanpeca** [comment]
>@goanpeca I created a new issue over at beefore and noticed you were working on pydoctest, maybe we could work together on integrating more tests.

Sounds good :-), but I will only be able to work on the weekend this week :-)

**Comment by danyeaw** [comment]
@freakboy3742 as part of this PR I also removed unused imports which adds some risk that I broke something that isn't being tested for. I could run through the examples in GTK+ and cocoa to increase confidence.

**Comment by danyeaw** [comment]
Ran through the examples and they are all working.

**Comment by danyeaw** [comment]
@freakboy3742 I updated the factories so they all have a consistent list of objects, and commented out the ones that aren't supported by each platform to act as the todo list. Why are the web, win32, and django factories in the __init__ modules instead of factory.py?

**Comment by freakboy3742** [comment]
@danyeaw Those modules haven't been updated to the new post-GSoC factory structure. win32 probably never will be; web is just a stub that I meant to build out but never have; and Django desperately needs some attention.

**Comment by freakboy3742** [comment]
@danyeaw Those modules haven't been updated to the new post-GSoC factory structure. win32 probably never will be; web is just a stub that I meant to build out but never have; and Django desperately needs some attention.

**Comment by danyeaw** [comment]
@freakboy3742 got it, thanks for the explanation. 👍

**Pull request merged**
