### PR TITLE
Update contribute.rst

### PR DESCRIPTION
**Pull request by ibigpapa**
Added addtional install step for windows.

Added to install the root of the git clone in windows.

This allows one to successfully install the demo
## PR Checklist:

- [ x ] All new features have been tested
- [ x ] All new features have been documented
- [ x ] I have read the **CONTRIBUTING.md** file
- [ x ] I will abide by the code of conduct

### CODE REVIEW

**Comment by ibigpapa** [comment]
I do not i think it might have something to do with running multiple editable links in windows under the same folder requires the their parent to also.   @freakboy3742 Actually helped me getting the demo to install.

**Comment by ibigpapa** [comment]
@phildini it looks like it is rooted in distutils.  And maybe a fix to the setup.py that might do the trick as well.
https://stackoverflow.com/questions/19602582/pip-install-editable-links-to-wrong-path?rq=1

**Comment by danyeaw** [comment]
@ibigpapa So should we close this PR then if this no longer seems to be the issue?

**Comment by ibigpapa** [comment]
@danyeaw I've not dived into seeing if this will fix it.

**Comment by freakboy3742** [comment]
I don't think we need to add this; it only came up in the context of running toga_demo with a development configuration after running "pip install toga-demo".

**Pull request closed without merging**
