### PR TITLE
Audited NumberInput and PasswordInput

### PR DESCRIPTION
**Pull request by Axle7XStriker**
PasswordInput was not getting initialized because the MIN_WIDTH variable was not set which is needed by the implementation. In NumberInput, the set_value() method was not handling TypeError perfectly since after the value was set to None it also tried to compare it with the min_value and max_value if they were not set to None which is impossible because of it a test related to test_set_value could not be defined previously. But now it's defined and the code coverage for numberinput.py is 100% now.

refs #299 

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by Axle7XStriker** [comment]
Now all that is left is to handle the None value in the implementation of the NumberInput. Maybe I am overthinking this, but I also wanted to know what should happen in case when a user assigns any other data type than int like a list to any attribute of NumberInput be it intentionally or by mistake.

**Comment by DariusMontez** [comment]
Don't worry, your not over thinking it - misuse handling is a sensitive
consideration for sure. As a general rule, if a given incorrect input
causes an exception to be thrown,  nothing needs to be done because the
user can reference the trace back. However, if the bad input causes
undesirable behavior without raising an exception, the API code should
manually implement type or value checking and either clean up the bad input
(i.e. bound a fraction between 0 and 1) or raise an exception if the input
is truly unusable. Does that help?

**Comment by Axle7XStriker** [comment]
Yes, I get your point however in cases where a variable is suppose to get an int and instead it is getting a string value though having the same value in it like 1 and '1', shouldn't an exception be thrown in the later case as it violates what is specified or should we clean up the bad input?

Also, I have noticed that in different widgets for certain types, value provided by the user is being cleaned in different manner though both gives the same result. I think if the similar kind of types are being handled across widgets, they should also be handled in a similar way in terms of the way code is written.

**Comment by Axle7XStriker** [comment]
I have fixed the test for NumberInput for when the value is set to a list wherein it should throw an error. But I did not fix other tests for incorporating the changes including the shift from int to decimal as I was thinking that since all the platforms have the same interface, we can have something like a utils file which would consist of all the sample data for all the data types in python and use that for writing platform specific tests. This way it would clean up the test directory for each platform and we can have tests implemented for all the platforms.
What do you think?

**Comment by freakboy3742** [comment]
I'm not quite sure I understand what you're suggesting with regards to an 'all sample data types' example file. If we're implementing the code right, we shouldn't need to do this testing on a per-platform basis, because set_value() is an internal API. We should be able to guarantee that the data reaching the implementation layer is already sanitised; if there are input validation tests, they should be performed at the interface layer.

**Comment by Axle7XStriker** [comment]
Ok, I think I got that but the thing which I was proposing can still be implemented within the core module, since we have to test that for every data type to ensure that each data type is handled correctly by the interface layer.

**Pull request merged**
